marriageweb:
    build: ./web
    container_name: marriageweb
    volumes:
      - ../web/src:/var/www
      - ../app/src/storage/app/avatars:/var/www/public/avatars
      - ./web/conf/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - marriageapp
      - marriagemysql
marriageapp:
    build: ./app
    container_name: marriageapp
    volumes:
            - ../app/src:/var/www
    ports:
      - "9000:9000"
    links:
      - marriagemysql
marriagemysql:
    image: mysql:latest
    container_name: marriagemysql
    ports:
         - "13306:3306"
    volumes:
            - ../db/working:/var/lib/mysql
    environment:
            - MYSQL_ROOT_PASSWORD=p2Z6JUxUQZmEj9La
